package ds.sudoku.communication;

/**
 * A connection manager listens for incomming connections,
 * accepts them and returns them as a new {@link Client}.
 * 
 * <p>The clients generated by the connection manager are
 * internally threaded. 
 */
public interface ConnectionManager {
	public void acceptConnections();
	public void acceptConnections(int maximumConnections);
	public void rejectConnections();
	
	public void setConnectionHandler(ConnectionHandler handler);
}
